server:
  port: 8887

github:
  client:
    id: dc364cf81cbdc28a0e43
    secret: ed0b52d1c11bf5d5b27d969570dc0b8688051cfc
  getaccesstoken:
    url: https://github.com/login/oauth/access_token
  getuser:
    url: https://api.github.com/user

callback:
  url: http://localhost:8887/callback

READ_TIMEOUT: 100
CONNECT_TIMEOUT: 60
WRITE_TIMEOUT: 60
DEFAULT_AVATAR: http://94.191.65.139/group1/M00/00/00/Xr9Bi16TJsCAKFamAAACk7pNBHw526_big.png

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://94.191.65.139:3306/community?useUnicode=true
    username: root
    password: wwwhao123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
#      是否只读
      read-only: false
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 60
      login-timeout: 5
      minimum-idle: 10

#fastdfs配置
fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:
    width: 150
    height: 150
  trackerList: 94.191.65.139:22122



mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    space:
      springboot:
        community:
          dao: debug
          mapper: debug